server:
  port: 8099



spring:
  datasource:
    url: jdbc:mysql://192.168.26.55:3306/xtj_monitor?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    org:
      springframework.web: info


# 摄像头配置
CAMERA:
  username: "admin"
  password: "hik12345"



# ftp 配置
FTP:
  username: "face"
  password: "face"
  serverIP: "10.119.116.170"
  serverPort: 21
  enableAnony: 0
  custdir: "face"


#抓图配置
snapshot:
  dwPicInterval: 4000 # 抓图时间间隔



