server:
  port: 8099


logging:
  level:
    org:
      springframework.web: info


# 摄像头配置
CAMERA:
  username: "admin"
  password: "hik12345"



# ftp 配置
FTP:
  username: "face"
  password: "face"
  serverIP: "10.119.116.170"
  serverPort: 21
  enableAnony: 0
  custdir: "face"


#抓图配置
snapshot:
  dwPicInterval: 4000 # 抓图时间间隔



